### ISSUE TITLE
[MANS-Deployment] [MC] : able to deploy MC package to Alpha everyday

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#100]
complete deployment operation via LRS
complete MNTool for create package and upload to BAMS.
complete MNTool to call mans-deployment to deploy to alpha (after create package)
compllete alpha dashboard for MC

**Comment by ruinfoe** [comment]
merge request
https://git.sami.int.thomsonreuters.com/upg_strategic_development/MNTool/merge_requests/1

**Comment by jobbo** [comment]
above merge request will resolve following process
complete MNTool for create package and upload to BAMS.
complete MNTool to call mans-deployment to deploy to alpha (after create package)
