### ISSUE TITLE
[MaNS-deployment] Inventory package that promoted from Jenkins to Alpha not show in promotion dashboard

### ISSUE THREAD

**Issue by ruinfoe** [jobbo/MNCProjects#120]

**Comment by jobbo** [comment]
If I remembered correctly, there was a hard-coded to pull to promotion list from 'dev' env currently, so the list from 'alpha' might not be shown due to this

**Comment by ruinfoe** [comment]
Not a bug, the cause is in the local machine is 'dev' env. so the list will get from deployed list as 'dev' env only not from alpha
