### ISSUE TITLE
[PX-Navigation] RP for PX expression service

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#131]
What we can do now before release to Beta and Prod is:
1) Create a reverse proxy endpoint for the service.
Currently we access to the service using direct url with port -> http://pcdtclamp01d.emea1.cis.trcloud:5555/resolveExpressions
It is better be a reverse proxy version like this -> http://pcdtclamp01d.emea1.cis.trcloud/applicability/resolveExpressions
The contact point is Pawel. Could you work with him making a reverse proxy version in Dev and Alpha server. Please make sure that the alpha endpoint one can be access from both cms-admin and cms-ws (Pawel should know how to do)

**Comment by ruinfoe** [comment]
done for dev,

merge request for alpha : https://github.com/thomsonreuters/cms-configurations/pull/200
