### ISSUE TITLE
[MANS-Deployment] [Inventory] : Create jenkin for calling deploy to NAS from MANS-Deployment

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#14]
- This will be a replacement for jenkin call Deployment to Alpha via Nolio
- schedule for Alpha deployment will be everyday

**Comment by ruinfoe** [comment]
link with http://jirag.int.thomsonreuters.com/browse/MAC-1287

**Comment by ruinfoe** [comment]
fixed by MANS-deployment version 0.0.5 and jenkins

http://nac.int.thomsonreuters.com:8080/view/Inventory%20deployment%20to%20alpha%20new%20flow/job/DeployInventoryToAlphaNewFlow/
