### ISSUE TITLE
[NavS] deploy applicability service to Prod

### ISSUE THREAD

**Issue by ruinfoe** [jobbo/MNCProjects#148]
server list : https://thehub.thomsonreuters.com/docs/DOC-608899

deployment process https://thehub.thomsonreuters.com/docs/DOC-1735223

1# complete release note
release note for latest version of applicability service 1.0.1

2# jenkin job and create prod rundeck
Project Applicability Service create PROD CR
project Applicability Service deploy release to PROD
Release Applicability service (rundeck for prod)

**Comment by ruinfoe** [comment]
have to wait this ticket apply on Prod

https://thehub.thomsonreuters.com/docs/DOC-1751753

**Comment by ruinfoe** [comment]
Is this story finished?

**Comment by jobbo** [comment]
now waiting for Performance test result #215
