### ISSUE TITLE
[MANS-Deployment] : enhance Promotion Tool

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#154]
fix issue that progress log blink between old and new request if we promote more than once, stop old polling status request when new release has been triggered 

clear progress log when click 'promote' confirmation

Eikon release dropdown - to default as 'Please select'

update the hub doc in progress log output

**Comment by ruinfoe** [comment]
merge request

https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS-lrs/merge_requests/30
https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS/merge_requests/33
