### ISSUE TITLE
[MANS-Deployment] : enhance Release Tool

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#155]
fix issue that progress log blink between old and new request, stop old polling status request when new release has been triggered

history tab should not show 'waiting' records

clear progress log when click 'deploy' confirmation

change Env in confirmation dialog to PhysicalEnv(Datacentor)

disable deploy button after confirm (currently disable after click deploy)

**Comment by ruinfoe** [comment]
merge request
https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS-lrs/merge_requests/31
https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS/merge_requests/34
