### ISSUE TITLE
[MaNS] Move mans service to EEM VM

### ISSUE THREAD

**Issue by ruinfoe** [jobbo/MNCProjects#165]
https://thehub.thomsonreuters.com/groups/ui-toolkit-application-server-team-resources/blog/2016/06/02/action-required-migrate-services-to-app-server-vms?et=notification.mention

**Comment by jobbo** [comment]
This might also affect the cut off plan to use new tool because we need to make sure the new VM that host LRS service will be working smoothly.

**Comment by ruinfoe** [comment]
Please note, currently, they don't have any plan to force service to move to EEM VM environment. But they just need test result/pilot user for Beta

**Comment by ruinfoe** [comment]
done by app server process
