### ISSUE TITLE
[NavS] stress test

### ISSUE THREAD

**Issue by ruinfoe** [jobbo/MNCProjects#168]
PX team need test result before they deploy their apps to Prod

**Comment by ruinfoe** [comment]
for exmaple : https://thehub.thomsonreuters.com/groups/bkk-ce-dev/blog/2016/06/07/formula-service-load-test-report

**Comment by jobbo** [comment]
https://thehub.thomsonreuters.com/groups/mac-nac-kt/blog/2016/06/16/applicability-service-load-test-report-on-beta-environment
