### ISSUE TITLE
[MANS-Deployment] : enhance release and promotion

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#177]
release
- to show deploy by and deploy time on releaseId that already deployed
- to show Physical Environment on history record
- add link step by step guide to thehub doc

promotion
- for project, sort record by version
- for history, sort record by time

**Comment by ruinfoe** [comment]
merge request https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS/merge_requests/39
