### ISSUE TITLE
Investigate MANS cache mechanism for resolveExpressions service

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#33]
# Message from Byrd

Hi P’Job,

In case many users request the same applicability expressions (Same request body, The only different is reuters id), How is the cache policy for this case (global cache or per user cache)?
Would be good if you can go in details about caching on MANS, There is a discussion among PX team whether PX should cache the applicable response as well or not?

Thanks and regards,
# Byrd

**Comment by ruinfoe** [comment]
MaNS resolve expression service use the same cache mechanism with other service. it's local cache in machine memory for all user.

Please note, resolve expression service is encode expression with md5 as base16 to be cache key.

**Comment by jobbo** [comment]
For resolveExpression service, there are 2 steps in the process that being cache (for reusability).

First one is Entity properties that get from Search service, this is cached per RIC

Second one is the resolveExpression result (applicable or not applicable), or in case that expression include some rule that relate to other than search entity (e.g. Eikon version / isEikonThin) the result will be cached in form of reduced result (the result that being left only part the cannot be cached), this is cached per expression + RIC

Both cache are global cache. And the cache will be generated as on Demand (cache occur when there is first time request for those RIC/ expression being used)
