### ISSUE TITLE
[MANS-Deployment] [Inventory] : [long-running] investigate process for fail safe scenario when perform Inventory deployment

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#34]
This will be mimic/ similar to TPM deployment instruction which include fail safe operation

**Comment by ruinfoe** [comment]
SPB deploy operations
- settings getting
- NAS share !mappedDrive!:\ mapped drive existence check
- setting full NAS share path
- files extraction
- NAS directory linking to !mappedDrive! drive
- successful mapped drive creation specifying
- previous !archiveNamePrefix!!VersionFolderName! temporary folder removal
- previous !mappedDrive!:!temporaryFullNasSharePath! temporary folder remove validation
- temporary Inventory folder copying
- previous !VersionFolderName! folder removal
- previous !mappedDrive!:!fullNasSharePath! folder remove validation
- NAS temporary folder renaming from !archiveNamePrefix!!VersionFolderName! to !VersionFolderName!
- NAS directory unlinking from !mappedDrive! drive

**Comment by ruinfoe** [comment]
settings getting operation
- get NAS sharing path from environment setting
- get NAS username and password from environment setting
- get Inventory Folder Name  from environment setting (if avaliable)

**Comment by ruinfoe** [comment]
NAS share !mappedDrive!:\ mapped drive existence check operation
- get all drive in machine
- if the drive is equal with machine config then check the drive mapped to the path as in the config

**Comment by ruinfoe** [comment]
setting full NAS share path
-  set destination extract path

**Comment by ruinfoe** [comment]
files extraction
- extract zip package by pkzip.exe with overwrite options

**Comment by ruinfoe** [comment]
NAS directory linking to !mappedDrive! drive
- link destination extract path to NAS

**Comment by ruinfoe** [comment]
successful mapped drive creation specifying
- set isMappedDriveWasSuccessfullyCreated property to true (1)

**Comment by ruinfoe** [comment]
previous !archiveNamePrefix!!VersionFolderName! temporary folder removal
- remove  temporary extract target path if exist.

**Comment by ruinfoe** [comment]
previous !mappedDrive!:!temporaryFullNasSharePath! temporary folder remove validation
- confirm that temporary extract target path does not exist.

**Comment by ruinfoe** [comment]
temporary Inventory folder copying
- copy extracted folder to temporary target on NAS

**Comment by ruinfoe** [comment]
previous !VersionFolderName! folder removal
- remove inventory target folder in NAS if exist

**Comment by ruinfoe** [comment]
previous !mappedDrive!:!fullNasSharePath! folder remove validation
- confirm that inventory target folder in NAS does not exist.

**Comment by ruinfoe** [comment]
NAS temporary folder renaming from !archiveNamePrefix!!VersionFolderName! to !VersionFolderName!
- rename inventory's temporary folder on NAS to target folder

**Comment by ruinfoe** [comment]
NAS directory unlinking from !mappedDrive! drive
- unlink temporary extract folder from map drive
