### ISSUE TITLE
[MANS-Deployment] [Inventory] : [UI Dashboard] handle concurrent use case for deployment scenario

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#35]
disable button for those version that being deployed.
for Prod (disable checkbox(es) for those data center that being deployed)

query deployment status from Mongo

**Comment by ruinfoe** [comment]
pull request: 

https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS-lrs/merge_requests/10

https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS/merge_requests/7
