### ISSUE TITLE
[MANS-Deployment] [Inventory] : [long-running] create persistent log and report mechanism

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#36]

**Comment by ruinfoe** [comment]
- done for persistent log
- report mechanism : email notification

**Comment by ruinfoe** [comment]
merge request : 
https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS/merge_requests/22
https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS-lrs/merge_requests/24
