### ISSUE TITLE
[MaNS] tab and rightClick result not same with the result from Views

### ISSUE THREAD

**Issue by ruinfoe** [jobbo/MNCProjects#56]

**Comment by ruinfoe** [comment]
pull request https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS-lrs/merge_requests/13

@jobbo , please help reviews

**Comment by jobbo** [comment]
Hi @ruinfoe 

Is this already on Alpha? Please help deploy it to Alpha and I will verify it on Alpha and close the story :+1:

**Comment by ruinfoe** [comment]
Hi @jobbo ,

Yes, this is ready on Alpha since 24 Feb 2016
