### ISSUE TITLE
[CDG] DSCMC-813

### ISSUE THREAD

**Issue by khaopun** [jobbo/MNCProjects#60]
Spot data for AUD Onshore source are EOD fixings >> Please remove those data from CDG

WT
AUD=AU must not be generated by CDG 

http://jirag.int.thomsonreuters.com/browse/DSCMC-813

**Comment by jobbo** [comment]
@khaopun is this one still applicable? 

please close if it isn't

**Comment by jobbo** [comment]
close untill needed
