### ISSUE TITLE
[MANS-Deployment] : Able to connect Mongo cloud DB and see History tab info

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#9]

**Comment by ruinfoe** [comment]
link with http://www.iajira.amers.ime.reuters.com/browse/MAC-1286

**Comment by ruinfoe** [comment]
merge request : https://git.sami.int.thomsonreuters.com/upg_strategic_development/MaNS-lrs/merge_requests/9

**Comment by ruinfoe** [comment]
P'Job @jobbo please review this

**Comment by jobbo** [comment]
passed!
