### ISSUE TITLE
[MANS-Deployment] [Metadata] : able to deploy metadata package to Alpha everyday

### ISSUE THREAD

**Issue by jobbo** [jobbo/MNCProjects#97]
complete deployment operation via LRS
complete MNTool for automatic create package and upload to BAMS  (MNTool has scheduling task module itself)
complete MNTool to call mans-deployment to deploy to alpha (after create package)
compllete alpha dashboard for Metadata

**Comment by ruinfoe** [comment]
merge request
https://git.sami.int.thomsonreuters.com/upg_strategic_development/MNTool/merge_requests/1

**Comment by jobbo** [comment]
above merge request will resolve following process
complete MNTool for automatic create package and upload to BAMS (MNTool has scheduling task module itself)
complete MNTool to call mans-deployment to deploy to alpha (after create package)
